<?php 
include 'header.phtml'; 
?>

<main class="container">
    <h2><i class="fa fa-pencil"></i> Editer un article</h2>

  
    <form class="generic-form" action="edit.php" method="post">

        <!-- champ caché pour spécifier à quel article rattacher le commentaire -->
        <input type="hidden" name="articleid" value="<?= intval($article['articleid']) ?>">

        <fieldset>
            <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
            <ul>
                <li>
                    <label for="title">Titre :</label>
                    <input type="text" id="title" name="title" value="<?= htmlspecialchars($article['title']) ?>">
                </li>
                <li>
                    <label class="textarea" for="content">Article :</label>
                    <textarea id="content" name="content" rows="15"><?= htmlspecialchars($article['content']) ?></textarea>
                </li>
                <li>
                    <button class="button button-primary" type="submit">Mettre à jour</button>
                    <a class="button button-cancel" href="index.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
    </form>


</main>
        

<?php 
include 'footer.phtml'; 
?>
